### ISSUE TITLE
[Issue] Registered views don't show in ItemsControl region

### ISSUE THREAD

**Issue by rmhw** [AvaloniaCommunity/Prism.Avalonia#101]
## Description
Registered views don't display in an ItemsControl region

## Environment
* **OS:**  Windows 10 and 11
*  **Prism.Avalonia Version:** 8.1.97.11000
* **Avalonia Version:** 11.0.2

## Severity (1-5)
3

## Steps To Reproduce
1. Designated an ItemsControl as a region
`<ItemsControl prism:RegionManager.RegionName="TestRegion" />`
2. Registered a view with the region
`regionManager.RegisterViewWithRegion("TestRegion", typeof(TestView1));
`regionManager.RegisterViewWithRegion("TestRegion", typeof(TestView2));`
3. Run the application - nothing appears in the ItemsControl
4. Change the ItemsControl to a ContentControl - TestView1 is shown.

## Expected Behavior
TestView1 and TestView2 should be displayed in the ItemsControl.

## Additional context
Having stepped through the code, the issue seems to come from ItemsControlRegionAdapter, where the following line sets ItemsSource to null.
`regionTarget.ItemsSource = region.Views as Avalonia.Collections.AvaloniaList<object>;`

**Comment by rmhw** [comment]
I've worked around this by implementing a callback approach based on https://github.com/DamianSuess/Learn.PrismAvaloniaOutlookish/blob/f6234acf7596e3e2c8dfa0ec72b2ed35c4295cda/source/SampleApp.Common/TabControlAdapter.cs, which seems to be working at first glance.

**Comment by DamianSuess** [comment]
@rmhw, from your implementation, do you think this should still be a part of Prism.Avalonia or at least a sample code piece?

**Comment by rmhw** [comment]
@DamianSuess Thanks for coming back to me.
Sure, happy to make a PR - are there any contributor guidelines I should be aware of?

**Comment by DamianSuess** [comment]
If you can add it to the `Samples\SampleMvvmApp` that would be great!

In upcoming releases (+9.x), I'd like to bring more `behavior` helpers as part of the main project. The reason this wasn't done sooner was due to concerns about having to support edge cases in other people's software.

Looking forward to your PR contribution, this will help teach others and be a nice asset to the project.

Thank you @rmhw

**Comment by dhhunter** [comment]
I ran into this problem just today using Prism.Avalonia 8.1.97.11000, any idea when the Release packages will be updated with the fixed ItemsControlRegionAdapter?  Thank you all for your hard work on this great package!
