### ISSUE TITLE
[Issue] The regionName defined in the current page does not appear in the OnNavieratedTo method call

### ISSUE THREAD

**Issue by yaobiao131** [AvaloniaCommunity/Prism.Avalonia#104]
## Description
A clear and concise description of what the bug is and include samples (using code blocks) if applicable.

## Environment
* **OS:**  _Windows 10, Ubuntu 22.04, etc._
*  **Prism.Avalonia Version:**
* **Avalonia Version:** 

## Severity (1-5)
1=Low (_annoyance_), 5=High (_crashes visual studio_)

## Steps To Reproduce
2. Click on '...'
3. Scroll down to '...'
4. Error message '...'

**Comment by DamianSuess** [comment]
It is required to provide a sample reproducing the error.
