### ISSUE TITLE
[Issue] Dependency on Avalonia.ReactiveUI

### ISSUE THREAD

**Issue by CrackAndDie** [AvaloniaCommunity/Prism.Avalonia#117]
## Description
I use Prism.Avalonia library and do not want to use the ReactiveUI. This is quite strange why do the library needs Avalonia.ReactiveUI

## Environment
* **OS:**  Windows 10
*  **Prism.Avalonia Version:** 8.1.97.11000
* **Avalonia Version:** 11.0.5

## Severity (1-5)
3

## Steps To Reproduce
1. Add the reference to *PrismAvalonia* to your project
2. There would be also the *Avalonia.ReactiveUI* linked

## Expected Behavior
I expect the *Prism.Avalonia* to be independent from *Avalonia.ReactiveUI*

## Screenshots
-

## Additional context
-

**Comment by DamianSuess** [comment]
Thank you for reaching out, @CrackAndDie.

I'll review your PR #118
