### ISSUE TITLE
[Issue] IDialogService.ShowDialog does not block ui-thread

### ISSUE THREAD

**Issue by SnakePliskin777** [AvaloniaCommunity/Prism.Avalonia#119]
## Description
IDialogService.ShowDialog does not block ui-thread

## Environment
* **OS:**  Windows 10, Debian 9
*  **Prism.Avalonia Version:** 8.1.97.11072
* **Avalonia Version:**  11.0.9

## Severity (1-5)
3

## Steps To Reproduce
```
            IDialogResult? result = null;
            _dialogService.ShowDialog(nameof(DialogView), new DialogParameters{{ "title", "Hi Dick Cunt!" } },
                r => { result = r;}); \\ not block
            Debug.WriteLine($"Dialog Result: {result?.Result}");  \\ result is null - no good
```

## Expected Behavior
IDialogService.ShowDialog should block the ui-thread, just like the vanilla Prism

**Comment by DamianSuess** [comment]
@SnakePliskin777  Thank you for reporting this. Though, S. D. Bob Plissken, would approve with a gravel voice, can you refrain from using strong language as this is a public repository.

**Comment by DamianSuess** [comment]
This is not a bug as per design.

We do not want to block the UI thread, thus freezing the app. The results are handled through eventing in the background, being called when the dialog closes as per the DialogService's `Show(...)` (non-modal) and `ShowDialog(...)` (modal) method's `Action` callback parameter. This is why you'll see the subsequent lines being executed before the dialog appears.

```cs
        _dialogService.ShowDialog(nameof(DialogView), new DialogParameters($"message={message}"), r =>
        {
            if (r is null)
            {
                Title = "Try again";
                ReturnedResult = "Null result returned";
            }

            ReturnedResult = r.Result.ToString();

            if (r.Result == ButtonResult.None)
                Title = "Result is None";
            else if (r.Result == ButtonResult.OK)
                Title = "Result is OK";
            else if (r.Result == ButtonResult.Cancel)
                Title = "Result is Cancel";
            else
                Title = "I Don't know what you did!?";
        });

        System.Console.WriteLine("Continues onward");
```
