### ISSUE TITLE
How to jump to the main page after login

### ISSUE THREAD

**Issue by OaimIsGnay** [AvaloniaCommunity/Prism.Avalonia#14]
https://github.com/AvaloniaUI/Avalonia/discussions/8194

**Comment by OmidID** [comment]
Hello @OaimIsGnay 
Please write more detail. 
The question you had in the Avalonia repository is confusing me. 
And the way you create the issue is not good. Please have a good title and describe your problem in the content. You paste a link with a no related to the title!!!!

**Comment by OaimIsGnay** [comment]
> Hello @OaimIsGnay Please write more detail. The question you had in the Avalonia repository is confusing me. And the way you create the issue is not good. Please have a good title and describe your problem in the content. You paste a link with a no related to the title!!!!

Hello. I just want to ask In prism, I can close the form after login and open the main form In another link, you can see code But in Avalonia, I don't know how to implement it

**Comment by OaimIsGnay** [comment]
![Uploading 11.jpg…]()

**Comment by OaimIsGnay** [comment]
In the prism, I do this
![image](https://user-images.githubusercontent.com/58240619/170606781-7445187a-fe3c-40ab-ba77-0fe1e3b504ce.png)

How do I implement it in Avalonia
![image](https://user-images.githubusercontent.com/58240619/170606844-69fa55fe-c292-4e26-b129-08a841ca4467.png)
