### ISSUE TITLE
How to modify it

### ISSUE THREAD

**Issue by OaimIsGnay** [AvaloniaCommunity/Prism.Avalonia#15]
<img width="594" alt="image" src="https://user-images.githubusercontent.com/58240619/171649606-559970fd-7dcc-4300-b2fc-43d75139525c.png">

**Comment by DamianSuess** [comment]
@OaimIsGnay, it appears you are trying to show the dialog box before the main window is fully rendered. Take a peek at the Avalonia docs for more assistance.

https://docs.avaloniaui.net/docs/controls/window
