### ISSUE TITLE
No regions at module initializing

### ISSUE THREAD

**Issue by EinApfelBaum** [AvaloniaCommunity/Prism.Avalonia#2]
In the overriden method on `IModule` `OnInitialized` the RegionManager has no regions.

    public void OnInitialized(IContainerProvider containerProvider)
    {
        var regionManager = containerProvider.Resolve<IRegionManager>();
        regionManager.Regions["ContentRegion"].Add(new ViewA());
     }

When the shell ist created and updates the regions, the visual parent is always null.

https://github.com/AvaloniaCommunity/Prism.Avalonia/blob/ff4e77276a10beb2915bd52fd09cc4ce79378a4a/src/Prism.Avalonia/Regions/Behaviors/RegionManagerRegistrationBehavior.cs#L142

When I debug Prism.Wpf, the RegionManager has regions at modul intializing.

I can provide an example, if needed.

**Comment by OmidID** [comment]
There are some different between WPF and Avalonia, 
I imagaine the Visual Parent is not exists until the application lifetime start.

**Comment by EinApfelBaum** [comment]
Yeah, it looks like the VisualTree is build after `(MainWindow as Window)?.Show();`.
I created a little sample app with a simple MainWindow:
````
<Window .......
    <Grid>
           <ContentControl prism:RegionManager.RegionName="ContentRegion"/>
    </Grid>
</Window
````
[https://github.com/EinApfelBaum/Prism.Avalonia.Samples/tree/master/src/07-ModulesRegions](https://github.com/EinApfelBaum/Prism.Avalonia.Samples/tree/master/src/07-ModulesRegions)

The visual parent (Grid) of the ContentControl is found. 
The visual parent of the Grid is null.
Interesting is, that the logical parent isnt null, the logical parent of Grid is MainWindow.

**Comment by OmidID** [comment]
Nice examples 👍 
I'll add a link to your repository 

This is how the Avalonia work. There is 2 way of starting the application Classic or Single View https://github.com/AvaloniaCommunity/Prism.Avalonia/blob/master/src/Prism.Avalonia/PrismApplicationBase.cs#L90
And until the root level is not started you don't have an application lifecycle.

**Comment by EinApfelBaum** [comment]
Yea, I ported some of the official Prism WPF Samples to Prism.Avalonia. Good practice for Prism and avalonia understanding. =)

With this behavoir some examples / usecases will not work. 
The example UsingCompositeCommands in the solution https://github.com/EinApfelBaum/Prism.Avalonia.Samples/tree/master/src/11-Commands is one of the use case. In the Module `OnInitialized` I want to add some Tab Views.

**Comment by jamsoft** [comment]
OK, this has properly thrown me off. Glad I found this chat.

Can we add a note to the main page as things like this mean the main ReadMe isn't actually correct as the development isn't the same as WPF if things like this don't work as per WPF Prism

**Comment by jamsoft** [comment]
Also, how did you manage this change?

I load a few views during the module `OnInitialized(IContainerProvider containerProvider)` method and am wondering how you got around this issue. TIA.

**Comment by DamianSuess** [comment]
@EinApfelBaum Since we've upgraded to support Prism v8.1.97, is this issue still happening, or are we good to close this?

**Comment by DamianSuess** [comment]
Marking issue as stale and closing
