### ISSUE TITLE
[Enhancement] Executes the specified animation when the view navigates

### ISSUE THREAD

**Issue by xiejiang2014** [AvaloniaCommunity/Prism.Avalonia#216]
Currently:
When navigating to a new view, the view switches directly without any transition effect.

Feature Request:
Ability to specify animation when navigating to a new view.
May need to perform 2 animations, one to exit the current view and the other to enter the new view.

**Comment by DamianSuess** [comment]
As amazing as this feature would be, it is out of the project's scope.
However, this could fall under the project, Prism.Avalonia.Toolkit which is in the early prototyping phase.

In the meantime, what Avalonia already provides:
* https://docs.avaloniaui.net/docs/guides/graphics-and-animation/page-transitions/how-to-create-a-custom-page-transition
* https://docs.avaloniaui.net/docs/0.10.x/animations/page-transitions
* https://docs.avaloniaui.net/docs/0.10.x/controls/transitioningcontentcontrol

**Comment by xiejiang2014** [comment]
I made an example:

[NavigationAnimationForPrism.Avalonia](https://github.com/xiejiang2014/NavigationAnimationForPrism.Avalonia)

**Comment by DamianSuess** [comment]
I love it, that looks beautiful!

@xiejiang2014  Would it be okay if we put that in as one of the samples?

**Comment by xiejiang2014** [comment]
> I love it, that looks beautiful!
> 
> @xiejiang2014 Would it be okay if we put that in as one of the samples?

Yes, of course.
