### ISSUE TITLE
Avalonia v11.0.0-prev4 - ViewModelLocator.AutoWireViewModel Issue

### ISSUE THREAD

**Issue by jmjcoelho** [AvaloniaCommunity/Prism.Avalonia#28]
Hi,

 I´m playing with the new version of Avalonia (ver. 11.0.0-preview4) and Prism ( because I use Prism in all my WPF and Xamarin projects), but when I run the Avalonia project it gives me a method not found exception on trying to auto wire the ViewModel, this is the line of code where the error occurs (prism:ViewModelLocator.AutoWireViewModel="True")

 This is the exception that I get:
`Method not found: 'System.IDisposable Avalonia.AvaloniaObjectExtensions.SetValue(Avalonia.IAvaloniaObject, Avalonia.AvaloniaProperty, System.Object, Avalonia.Data.BindingPriority)'.`

I'm not sure if this is a Pirsm or Avalonia issue.

Regards
José Coelho

**Comment by DamianSuess** [comment]
@jmjcoelho, thank you for reporting this.  At this time, we are working towards supporting the upcoming release of Avalonia v11.0, as the current NuGet package only supports v0.10.x.

Initial upgrade runs do show that we need to do a bit of extra work to support the future release of Avalonia.

Out of curiosity, was this the only error you encountered thus far?

**Comment by jmjcoelho** [comment]
Hi Damian,

 I also gives the same error when binding the region, on the main view,
 `
			<ContentControl Grid.Row="0"
							Grid.Column="1"
							prism:RegionManager.RegionName="{x:Static core:RegionNames.ContentRegion}" />`
