### ISSUE TITLE
Support Avalonia 0.10

### ISSUE THREAD

**Issue by renewal-wu** [AvaloniaCommunity/Prism.Avalonia#3]
Prism.Avalonia do not support Avalonia 0.10 currectly, do you have any plan to let Prism.Avalonia support Avalonia 0.10?

**Comment by OmidID** [comment]
Hello, Yes I have a plan to migrate it. But as I busy with something else now maybe it takes time.

**Comment by buldo** [comment]
@OmidID I creates PR #4

**Comment by OmidID** [comment]
@buldo Thank you so much. :)
Until tomorrow I'll do some test and upload packages

**Comment by OmidID** [comment]
Nuget updated as well
