### ISSUE TITLE
project templates

### ISSUE THREAD

**Issue by sabuto** [AvaloniaCommunity/Prism.Avalonia#34]
Hi,

I am looking into creating some project templates for Prism.Avalonia I just want to make sure that there are none out there already that i may be missing? From what I can see there are none apart from the standard avaloniaui templates.

**Comment by DamianSuess** [comment]
@sabuto, go for it.
Though I do have a sandbox project started for one, my current efforts have been geared toward Avalonia v11 (preview) support, and then back to that.

**Comment by sabuto** [comment]
Awesome I'll have a go, not a problem moving it sorry I didnt put it in the correct place!

**Comment by sabuto** [comment]
Please see discussion here 

https://github.com/AvaloniaCommunity/Prism.Avalonia/discussions/37
