### ISSUE TITLE
RegionManager doesn't contain Region when app Initialize

### ISSUE THREAD

**Issue by Sawa121212** [AvaloniaCommunity/Prism.Avalonia#35]
I have a WPF application.
I did almost the same, but there is a catch in the initialization:
The Region Manager does not contain a region.

I am attaching the smallest part of the projects.
[CustomTabControlRegionAdapter.zip](https://github.com/AvaloniaCommunity/Prism.Avalonia/files/10245999/CustomTabControlRegionAdapter.zip)
[CustomTabControlRegionAdapter_Avalonia.zip](https://github.com/AvaloniaCommunity/Prism.Avalonia/files/10246000/CustomTabControlRegionAdapter_Avalonia.zip)

**Comment by DamianSuess** [comment]
@Sawa121212, apologies for the late reply (_holiday break_).  Are you still having this issue or were you able to work resolve it?

As a side note, though Prism.Avalonia is similar to it's WPF counterpart, there are some settle differences due to the inherit nature of Avalonia's framework.

**Comment by Sawa121212** [comment]
I made a separate registration in the ViewModel
