### ISSUE TITLE
[Enhancement] Update to Avalonia 11.0-Preivew 6

### ISSUE THREAD

**Issue by rabbitism** [AvaloniaCommunity/Prism.Avalonia#49]
## Description

Below changes made RegionManager not compatible with Avalonia preview6. The package need to be updated. 
https://github.com/AvaloniaUI/Avalonia/commit/4fc1995246b2e35574a95e7f7be61d27dc2cc144

**Comment by DamianSuess** [comment]
Thank you @rabbitism for the heads up. Putting 11.0-Preview 6 on the backlog. If you have any suggestions for the changes needed, feel free to create a PR.

As of 3hrs ago, looks like we got to test and get a new build for v0.10.19 as well

**Comment by rabbitism** [comment]
I just want to confirm, there are currently 29 failed tests in develop branch, is that expected?

**Comment by DamianSuess** [comment]
That is correct

**Comment by DamianSuess** [comment]
Fat-fingered the close button by accident

**Comment by rabbitism** [comment]
I think there isn't much to update, I just updated the dependency. Can you create a feature branch so I can create PR? 
Or it's too simple that you can just do it here directly 🤣

**Comment by DamianSuess** [comment]
Sorry for the late reply, @rabbitism, I was traveling.
You should be able to fork it and create a branch on your end, followed by a PR. Let me know if there are any issues

**Comment by DamianSuess** [comment]
Closing as part of PR #61
