### ISSUE TITLE
Project Templates

### ISSUE THREAD

**Issue by furesoft** [AvaloniaCommunity/Prism.Avalonia#5]
Please create VS Templates to make it easier to start with Prism.Avalonia

**Comment by OmidID** [comment]
Good idea. Maybe dotnet template would be better to be reusable everywhere.

**Comment by DamianSuess** [comment]
Discussion #37 takes care of this item

**Comment by DamianSuess** [comment]
Since Avalonia is still in the Preview/RC phase, I'm going to release this using Prism.Avalonia v8.1.97.1021 as the base library and once v11.0 becomes GA, I'll upgrade it accordingly.

**Comment by DamianSuess** [comment]
Tracking this issue in https://github.com/AvaloniaUI/TemplateStudio/issues/10
