### ISSUE TITLE
[Issue] Avalonia.Desktop and Avalonia.ReactiveUI shouldn't be library dependencies

### ISSUE THREAD

**Issue by maxkatz6** [AvaloniaCommunity/Prism.Avalonia#55]
## Description

Avalonia.Desktop is an optional package for the desktop apps only. It won't cause problems on mobile, but on Browser backend it cannot be compiled.
Avalonia.ReactiveUI is an optional package, integration with ReactiveUI, alternative for [Prism.Avalonia](https://github.com/AvaloniaCommunity/Prism.Avalonia). Most users won't need to reference or use both.

## Environment
* **OS:**  any
*  **Prism.Avalonia Version:** v8.1.97.2
* **Avalonia Version:** 11.0

## Severity (1-5)
4 (compile time error)

## Steps To Reproduce
1. Create avalonia-xplat template
2. Reference Prism.Avalonia
3. Run Browser project

## Expected Behavior

It compiles.

## Additional context

Reminded by this comment https://github.com/AvaloniaUI/Avalonia/discussions/9264#discussioncomment-5669490

**Comment by DamianSuess** [comment]
Great observation and reference, @maxkatz6. Thanks for looking out for us.. spinning up a branch now to reduce dependencies

**Comment by DamianSuess** [comment]
As per your request, `Avalonia.Desktop` has been moved out of the core and only referenced by the sample desktop applications. 

As for, `Avalonia.ReactiveUI`, is a dependency of the `ViewModelLocator`, `RegionManager`, `ObservableObject`, `ItemMetadata`, and `Dialog` classes which utilize a flavor of `(AvaloniaProperty).Changed.Subscribe(args => ...);`

Much appreciated, Max

**Comment by maxkatz6** [comment]
> As for, Avalonia.ReactiveUI, is a dependency of the ViewModelLocator, RegionManager, ObservableObject, ItemMetadata, and Dialog classes which utilize a flavor of (AvaloniaProperty).Changed.Subscribe(args => ...);

Shouldn't be an issue. If it's a simple scenario, you can use:
`Changed.Subscribe(new AnonymousObserver(args => ...))`

If it's a more complex scenario, and you use more members from reactive assembly, you can reference System.Reactive package instead. This one was used in Avalonia.Core before as well.

**Comment by maxkatz6** [comment]
Also, is Avalonia.Markup.Xaml.Loader used in Prism? It's used to dynamically parse XAML files.
