### ISSUE TITLE
[Issue] base. Initialize() does not display xaml views

### ISSUE THREAD

**Issue by OaimIsGnay** [AvaloniaCommunity/Prism.Avalonia#58]
**Adding this code will cause xaml to be unable to preview.**

<img width="513" alt="image" src="https://user-images.githubusercontent.com/58240619/234183926-bbdbab9b-8036-4e4e-ab4b-a7d636763806.png">
<img width="1574" alt="image" src="https://user-images.githubusercontent.com/58240619/234183878-25ce7aba-e59e-4f25-aaaf-ba206f7d1204.png">

**Removing this line can display normally.**

<img width="427" alt="image" src="https://user-images.githubusercontent.com/58240619/234184012-51dcde5d-0024-4ded-aee4-72bfac23683a.png">
<img width="1204" alt="image" src="https://user-images.githubusercontent.com/58240619/234184190-ed0f40b2-8cfe-4a0e-9074-1347fc97f82e.png">

**Comment by OaimIsGnay** [comment]
If I remove it, I won't be able to see the form when the program starts

**Comment by OaimIsGnay** [comment]
If I don't remove it, I won't be able to see the preview interface again

**Comment by hafzaal** [comment]
I have this issue as well on the latest release candidate for v11. The designer doesn't show any previews when Prism is loaded. Without loading prism the designer works as expected.

**Comment by DamianSuess** [comment]
@hafzaal interesting. If you download the repository and open one of the sample projects (_i.e. SampleMvvmApp_), do you have the same issue?
