### ISSUE TITLE
Multiple instances of the same interface cannot be obtained

### ISSUE THREAD

**Issue by xyaoo** [AvaloniaCommunity/Prism.Avalonia#7]
Register Types in the App.xaml.cs like this:
![批注 2021-07-27 143538](https://user-images.githubusercontent.com/34727649/127107372-a3f4b2e8-cc98-4a06-b430-412b81b0e0ee.png)
There was an error I call serviceProvider.GetServices<IAlarm>()
![批注 2021-07-27 144201](https://user-images.githubusercontent.com/34727649/127107959-6daaebcb-41fa-4cec-a5f0-a8ff97c7e134.png)
serviceProvider.GetService is OK. However, only the latest registration can be obtained.
Does this not support multiple instances?
Would you please upgrade Prism to 8.0+ on Nuget. Thank you!

**Comment by OmidID** [comment]
Hello, Sorry that I answer late
What I see here it should work https://github.com/AvaloniaCommunity/Prism.Avalonia/blob/master/src/Prism.DryIoc.Avalonia/Ioc/DryIocContainerExtension.cs

As you see this is register normally. I need more details and I need to know what is the IoC you are using.

**Comment by xyaoo** [comment]
ioc is Dryioc
![批注 2021-08-09 100312](https://user-images.githubusercontent.com/34727649/128653701-b25e0c26-a37d-4066-b753-e9285861f121.png)

Prism.Dryioc.Extensions has been updated to 8.0.62, But Prism.Dryioc.Avalonia has not been updated, so I still use 7.2 for Prism.Dryioc.Extensions.

**Comment by OmidID** [comment]
Prism 8 is not supported yet.

For me would be easier if you send a project example somewhere on Github. That could help to find what is the problem.

What I see in your screenshot, it is shown that you never register any IAlarm service.

**Comment by DamianSuess** [comment]
@xyaoo, has your issue been resolved? Thank you
