### ISSUE TITLE
dialog settings parameters do not works

### ISSUE THREAD

**Issue by JIIIIL** [AvaloniaCommunity/Prism.Avalonia#80]
The dialog pops up normally after registration, but the Settings window does not take effect

<UserControl
    x:Class="AvaloniaApplication5.Views.DialogHost"
    xmlns="https://github.com/avaloniaui"
    xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
    xmlns:d="http://schemas.microsoft.com/expression/blend/2008"
    xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006"
    xmlns:prism="http://prismlibrary.com/"
    d:DesignHeight="450"
    d:DesignWidth="800"
    mc:Ignorable="d">
    <prism:Dialog.WindowStyle>
        <Style Selector="Window">
            <Setter Property="Width" Value="1366" />
            <Setter Property="Height" Value="768" />
        </Style>
    </prism:Dialog.WindowStyle>
    DialogHost
</UserControl>

![image](https://github.com/AvaloniaCommunity/Prism.Avalonia/assets/83105448/ad1ddfde-4af1-4ed4-8786-b97cdc8f8302)

**Comment by DamianSuess** [comment]
At this time custom window property styles - _i.e. Prism.WPF_ - are not supported.
If this is a feature you would like to see added, please feel free to create an enhancement PR.

**Comment by JIIIIL** [comment]
thank
