### ISSUE TITLE
Upgrade to Prism 8.1.97

### ISSUE THREAD

**Issue by DamianSuess** [AvaloniaCommunity/Prism.Avalonia#9]
As a user, I'd like to use the latest Prism framework with Prism.Avalonia which supports .NET 5, Linux and includes newer features. Figured this story would help keep the ball rolling and a discussion flowing. 👍 

Thus far, the upgrade is nearly straightforward comparing [Prism Library v7.2.0.1422...v8.1.97](https://github.com/PrismLibrary/Prism/compare/v7.2.0.1422...v8.1.97). However, there are some speedbumps that were bound to happen.  The focus of comparison thus far is the project, `Prism.Wpf`.

Upgrade Progress: [Upgrade-Prism-7.2-to-8.1.md](https://github.com/AvaloniaCommunity/Prism.Avalonia/blob/feature-Prism8197/Upgrade-Prism-7.2-to-8.1.md)
Local Pull Request: #11

If any of you have some insight into issues found along the way denoted by the `⚠️` symbol in the [Upgrade file](https://github.com/AvaloniaCommunity/Prism.Avalonia/blob/feature-Prism8197/Upgrade-Prism-7.2-to-8.1.md), please join in to help keep this moving.

### Action Items

* [X] Upgrade Prism.Avalonia
* [X] Upgrade Prism.DryIoc
* [x] Upgrade Prism.Unity
* [X] Remove IOCs not supported by Prism v8.1
* [X] Upgrade Samples
* [x] Add Unit Tests, matching PrismLibrary

### Out of Scope

* Restructure folders to match PrismLibrary
* Add Prism Dialogs for Avalonia

### Speedbumps
* `ModuleCatalog.cs`
    * Cannot use ContentPropertyAttribute such as `[ContentProperty("Items")]` - (_Already addressed in 7.2.x_)
    * Cause: ContentPropertyAttribute references System.Windows.Markup and Avalonia.Markup.Xaml doesn't have one

### Updates
* 2021-09-07 - Changed links to point at this repo's branch, now that it is housed here.

**Comment by OmidID** [comment]
Hello @DamianSuess,
Sure, I'll take a look. Thanks for participating

**Comment by DamianSuess** [comment]
I'm thinking with all of the files being touch, it may be helpful to make an Upgrade Matrix listing files with the following columns: **File Name, Is Updated, Has Errors**  (_and possibly New/Removed_)

**Comment by OmidID** [comment]
@DamianSuess I see that you create the PR on your repository. Can you make a PR here?

**Comment by DamianSuess** [comment]
@OmidID I was hoping to be able to dedicate more time to the upgrade process. I'm still keeping an eye on it, just got busy at the day job (_which is using this project_). Going to squeeze in more off-hours to commit towards this effort.

**Comment by OmidID** [comment]
Thank you so much for contributing. Same here, I am so busy for the moment but I really happy that you started.

**Comment by DamianSuess** [comment]
@OmidID, since Autofac is no longer supported by PrismLibrary, do you want this folder removed or keep it around for a later upgrade?

**Comment by OmidID** [comment]
@DamianSuess  That package is already is out of date and your right. Let's delete the entire folder.

**Comment by DamianSuess** [comment]
Cool, thanks. Didn't want to make a move without your approval ;)

**Comment by DamianSuess** [comment]
@OmidID ok, so I made a huge step in progress today & with current status [reflected here](https://github.com/DamianSuess/Prism.Avalonia/blob/feature-Prism8197/Upgrade-Prism-7.2-to-8.1.md).

Right now it could use a 2nd set of eyes on the items marked with a ⚠️. These errors are all Avalonia related.

As a 1st-pass, I'm focusing only on DryIoc, followed by Unity next.

**Comment by OmidID** [comment]
Amazing. Nice progress. I really would like to make some free time to join you as well.
I think it would be much better if push all changes in this repo feature branch. If someone wants to help then would be easier.

**Comment by DamianSuess** [comment]
Thank you, I appreciate the invitation, @OmidID. Yes, that would make things easier indeed 😄 
Today is our Labor Day celebration here in the states, when I get settled in, I'll push up the branch here.

**Comment by xyaoo** [comment]
Can you update the Nuget package? @DamianSuess

**Comment by DamianSuess** [comment]
@xyaoo, the package will be updated as soon as the feature is finished.
Feel free to monitor the status via [Upgrade-Prism-7.2-to-8.1.md](https://github.com/AvaloniaCommunity/Prism.Avalonia/blob/feature-Prism8197/Upgrade-Prism-7.2-to-8.1.md) and assist on any item marked as incomplete.

**Comment by DamianSuess** [comment]
Made forward progress on the build. Working on the sample projects and patches along the way.

Currently, the DialogService has been disabled while core functionality is the primary focus.

**Comment by OmidID** [comment]
@DamianSuess Great job :+1: 
Currently, I working on Linux, and boot Drm super fast for embedded devices. After I finish with that project and publish then I can help with this.

**Comment by DamianSuess** [comment]
Wonderful, thank you @OmidID. Hope your project comes through nicely for you

**Comment by OmidID** [comment]
Wow. Wonderful. 
For the first release, you can publish it without Unit-test maybe. 
After the release maybe is a good idea to ask the Prism team to publish it officially.

**Comment by DamianSuess** [comment]
I'm good with that 👍 
What are your thoughts on releasing this without the IDialogService and we patch it in with a small service release? This way we can keep this repository moving forward and ensure stability for the community.

**Comment by DamianSuess** [comment]
@OmidID, when you get a chance, please give this a test drive and let me know which features or changes are still required prior to merging this into the master branch.  My work schedule finally allowed for some after-hours coding again for the next couple of weeks ;)

The `BasicMvvmApp` sample demonstrates navigation into Regions, passing parameters, and Journaling for navigating back.  It's TargetFramework is .NET 6, where-as the other samples are set to .NET 5.

**Comment by OmidID** [comment]
Hello @DamianSuess, great job. 
I agree with you. We can create a beta release and continue fixing bugs.

Maybe we can update everything to .Net6?

**Comment by DamianSuess** [comment]
Thanks @OmidID. Sure, I can update the samples to .Net 6.. give me a few minutes and it will be pushed up.

The Unit Tests upgraded pretty nicely too. When you run them, you'll see some of the failures are Garbage Collection related. I'm wondering if this is a WPF vs Avalonia kind of thing, where this is an Avalonia issue and not Prism.Avalonia related.

**Comment by DamianSuess** [comment]
@OmidID, the PR is ready for review and merging when you are, sir. 👍

**Comment by OmidID** [comment]
WOAAAAA. AMAZING :+1: 
GREAT JOB. Actually, I change your role to admin and you can apply any changes to the repository. :D 
I am really excited that you did it.

**Comment by OmidID** [comment]
What is your username in Nuget?

**Comment by DamianSuess** [comment]
@OmidID, hope you don't mind, i'm gonna close this item out since PR #11 has been completed & open a new one for the IDialogService feature.

**Comment by DamianSuess** [comment]
That would be wonderful if it is accepted. It would make things much easier for community downloads to be tied into one source and we can continue supporting it from there.
