### ISSUE TITLE
The tabcontrol can not work

### ISSUE THREAD

**Issue by Red6789** [AvaloniaCommunity/Prism.Avalonia#92]
src/Prism.Avalonia/Regions/Behaviors/SelectorItemsSourceSyncBehavior.cs
This code is not implemented, so the RegionName attribute cannot be applied to the TabControl, what should I do?
![image](https://github.com/AvaloniaCommunity/Prism.Avalonia/assets/131952234/7d64a8cd-e714-473b-a300-41dd9a01aa3d)

**Comment by DamianSuess** [comment]
@Red6789, a couple of questions before we dive into it:

* Is this an issue or a discussion question? If it's a code question, please post in Discussions.
* What versions of Prism.Avalonia and Avalonia are you using?
* What is your code attempting to accomplish?

**Comment by DamianSuess** [comment]
@Red6789 checkout Discussion topic https://github.com/AvaloniaCommunity/Prism.Avalonia/discussions/88#discussioncomment-6609864 where your concerns may be addressed.
