### ISSUE TITLE
[Issue] Navigation journal broken

### ISSUE THREAD

**Issue by flexxxxer** [AvaloniaCommunity/Prism.Avalonia#98]
## Description
I have `ContentControl` with region name on `MainView`, in this `ContentControl`  i putting `FirstView`. In the `FirstView` the is button "Go next" which performing `IRegionManager.RequestNavigate` on `SecondView`. In the `SecondView` the is buttons "Go next" and "Go back", where "Go next" performing `IRegionManager.RequestNavigate` on `ThirdView` and "Go back" performing `IRegionNavigationJournal.GoBack` if its possible (mean `IRegionNavigationJournal.CanGoBack` is `true`). In the `ThirdView` the is button "Go back" which performing `IRegionNavigationJournal.GoBack` if its possible. Problem in fact that `IRegionNavigationJournal.CanGoBack` is `false` for `SecondView` BUT in same time `IRegionNavigationJournal.CanGoBack` is `true` for `ThirdView` (as expected). Example avalonia app in this repo: https://github.com/flexxxxer/Prism.Avalonia.NavigationBug

## Environment
* **OS:**  _Windows 11
*  **Prism.Avalonia Version:** 8.1.97.11000
* **Avalonia Version:** 11.0.4

## Steps To Reproduce
1. Clone repo: https://github.com/flexxxxer/Prism.Avalonia.NavigationBug
2. Run `Avalonia.NavigationBug.Desktop`
3. Click "Go next"
4. Click "Go back" - not performing.

## Expected Behavior
On the step 4 "Go back" switching view to previous one.

## Screenshots
https://github.com/AvaloniaCommunity/Prism.Avalonia/assets/44833369/568a1d7d-e11a-4289-b54a-ce00b492f365

**Comment by DamianSuess** [comment]
Thank you @flexxxxer for including a video and sample repo with the issue you're encountering to assist with troubleshooting your issue.

Though I do not have time to look too deeply into your issue immediately, I saw your issue notification and wanted to let you know it is on the radar. Overall, this system follows the same rules as Prism.WPF and I provided some reference material below of what I was able to gather skimming across your code.

## References

* [Prism Navigation Journal](https://prismlibrary.com/docs/wpf/region-navigation/navigation-journal.html)
> **Note:** The navigation journal can only be used for region-based navigation operations that are coordinated by the region navigation service. If you use view discovery or view injection to implement navigation within a region, the navigation journal will not be updated during navigation and cannot be used to navigate forward or backward within that region.

I can see in your code, it's going directly to, `FirstView` in the App.xaml.cs, and therefore not allowing `OnNavigatedTo(...)` to get triggered.

```cs
 protected override void OnInitialized()
  {
    var regionManager = Container.Resolve<IRegionManager>();
    regionManager.RegisterViewWithRegion<FirstView>(RegionNames.Content);
    
    base.OnInitialized();
  }
```

* [Sample MVVM App](https://github.com/AvaloniaCommunity/Prism.Avalonia/tree/develop/samples/SampleMvvmApp)


```cs
        private void DoNavigate(Uri source, Action<NavigationResult> navigationCallback, INavigationParameters navigationParameters)
        {
            ...
            RequestCanNavigateFromOnCurrentlyActiveView(
                _currentNavigationContext,
                navigationCallback,
                Region.ActiveViews.ToArray(),
                0);
        }

        private void RequestCanNavigateFromOnCurrentlyActiveView(
            NavigationContext navigationContext,
            Action<NavigationResult> navigationCallback,
            object[] activeViews,
            int currentViewIndex)
        {
            if (currentViewIndex < activeViews.Length)
            {
                ...  // Your initial navigation is going here and not being picked up by ExecuteNavigation(...) which creates an entry in the Journal Stack
            }
            else
            {
                ExecuteNavigation(navigationContext, activeViews, navigationCallback);
            }
```

**Comment by flexxxxer** [comment]
As far as I understand, this is a design problem in Prism.WPF, which Prism.Avalonia follows, and I can’t fix this on my part without solving this problem in the source code of Prism.WPF and then Prism.Avalonia?

**Comment by DamianSuess** [comment]
To assist with this navigation implementation issue you're running into, I created a Prism.WPF equivalent based on the sample code provided and it does navigate forward/backward in the same manner as your sample video, stopping at the `SecondView`.

> https://github.com/DamianSuess/Learn.PrismLibrary/tree/master/Wpf-Ex5-NavigationJournal

Prism.Avalonia aims to be compliant with the Prism library's architecture so that developers can quickly hop between other GUI frameworks that may use Prism.Uno and Prism.WPF. I do suggest posting an inquiry with the guys in the main library's Issue or Discussion board if you feel this needs to be an architecture change.

Currently, there are strides forward in the main library where they are consolidating the Region Interfaces to the main Prism.Core. 
https://github.com/PrismLibrary/Prism/issues/2935
